app = "cnn-deduplication-api"
primary_region = "iad"  # Change to your preferred region

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "cnn_data"
  destination = "/app/photo"